"""Estimator-style API for Rashomon Importance Distribution analyses."""

from .core import (
    CrossFamilyRashomonImportanceDistribution,
    RashomonImportanceDistribution,
    VALID_CROSS_FAMILY_BALANCE_MODES,
    VALID_PERFORMANCE_METRICS,
    VALID_VI_METRICS,
    compute_coef_importance,
    compute_loco_importance,
    compute_model_reliance,
    compute_rid,
    compute_rid_cross_family,
    performance_accuracy,
    performance_auprc,
    performance_f1,
    summarize_metric_result,
    vi_coef,
    vi_loco,
    vi_sub_mr,
)
from .models import (
    ElasticNetClassifier,
    GridCandidateTrainer,
    LassoClassifier,
    LinearClassifier,
    RidgeClassifier,
    SingleCandidateTrainer,
    TRAINER_REGISTRY,
    register_candidate_trainer,
    resolve_candidate_trainer,
    resolve_model_config,
)

__all__ = [
    "CrossFamilyRashomonImportanceDistribution",
    "ElasticNetClassifier",
    "GridCandidateTrainer",
    "LassoClassifier",
    "LinearClassifier",
    "RashomonImportanceDistribution",
    "RidgeClassifier",
    "SingleCandidateTrainer",
    "TRAINER_REGISTRY",
    "VALID_CROSS_FAMILY_BALANCE_MODES",
    "VALID_PERFORMANCE_METRICS",
    "VALID_VI_METRICS",
    "compute_coef_importance",
    "compute_loco_importance",
    "compute_model_reliance",
    "compute_rid",
    "compute_rid_cross_family",
    "performance_accuracy",
    "performance_auprc",
    "performance_f1",
    "register_candidate_trainer",
    "resolve_candidate_trainer",
    "resolve_model_config",
    "summarize_metric_result",
    "vi_coef",
    "vi_loco",
    "vi_sub_mr",
]